- devices/Hcsr04/Hcsr04.cs
- devices/Hcsr04/Hcsr04.nfproj
- devices/Hcsr04/Hcsr04.nuspec
- devices/Hcsr04/Hcsr04.sln
- devices/Hcsr04/README.md
- devices/Hcsr04/packages.config
- devices/Hcsr04/samples/Hcsr04.Samples.nfproj
- devices/Hcsr04/samples/Program.cs
- devices/Hcsr04/samples/packages.config
Adjusting HCSR04 to be used with one pin
- Adjusting HCSR04 to be used with one pin
- Used in the MagicBit bot where the sensor is using only 1 pin
On a real sensor
> Adjusting HCSR04 to be used with one pin

- devices/Hcsr04.Esp32/Hcsr04.Esp32.cs
The max range of the sensor is 4m, not 0.4m.
As defined in the datasheet, the max range of the sensor is 4m.
The validation if the measurement is out of range has been corrected from 0.4 to 4.
Without the fix, only measurements up to 40cm are measured. 
For higher distances, which are still in the valid range of the sensor, the library reports an invalid measurement.
Tested with real device.
> Fixed max range for Hcsr04.ESP32

- devices/Ws28xx/Ws28xx.nfproj
- devices/Ws28xx/Ws28xx.nuspec
- devices/Ws28xx/packages.config
- devices/Ws28xx/samples/Ws28xx.Samples.nfproj
- devices/Ws28xx/samples/packages.config
Updated dependencies for device WS28xx so that there are not assembly mismatch when using the current mscorlib
> Fix dependencies for device WS28xx

- devices/AtomQrCode/QrCodeReader.cs
- Add missing initialization in guard flag.
- Add missing reset in flag.
> Fix exceptions when using continuous reading

- devices/System.Buffers.Binary.BinaryPrimitives/BinaryPrimitives.cs
- tests/BinaryPrimitivesUnitTests/BinaryPrimitivesTests.cs
* Add assignment to the correct type in ReadSingle*() methods
* Add test to capture this problem in the future
Only in release builds, and also only when the result of the ReadSingle*() was not assigned to a float (but anything else, like double), the assigned value would be its underlying uint value.
A forced assignment in the ReadSingle*() functions fixes this problem for release builds. The test has been updated to capture this edge case.
The problem can be reproduced if you revert the changes in `BinaryPrimitives.cs` and then run the tests in Release mode.
* Found and confirmed fixed in a practical application using the SPS30
* By updating the relevant testcases
> BinaryPrimitives: Fix ReadSingle*() in Release build

- devices/Ws28xx.Esp32/Ws2812B.cs
according to documentation and my calculations - which might be wrong..
- during testing Esp32 WS2812b I found that "more" LEDs than supposed to were starting to light up - all of them in a yellow to orange hue.
- using basically the code from [here](https://github.com/ivan0414/nanoFramework.WS2812/tree/master/nanoFramework.WS2812/WS2812) with slight adaptions, results in the right number of LEDs lighting up. 
- According to the documentations I found [online](https://www.arrow.com/en/research-and-events/articles/protocol-for-the-ws2812b-programmable-led) and linked in the [Ws28xx Readme](https://github.com/nanoframework/nanoFramework.IoT.Device/tree/develop/devices/Ws28xx) for [Ws2812b](https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf) the timings for the pulses were slightly off - …
> Fix pulse timings for Ws2812b for ESP32

- devices/Ft6xx6x/samples/Ft6xx6x.Samples.nfproj
- devices/Ft6xx6x/samples/packages.config
- devices/Ft6xx6x/samples/packages.lock.json
Bumps nanoFramework.M5Core2 from 1.1.78 to 1.1.82</br>Bumps UnitsNet.nanoFramework.ElectricCurrent from 4.147.0 to 4.148.0</br>Bumps UnitsNet.nanoFramework.ElectricPotential from 4.147.0 to 4.148.0</br>Bumps UnitsNet.nanoFramework.Power from 4.147.0 to 4.148.0</br>Bumps UnitsNet.nanoFramework.Temperature from 4.147.0 to 4.148.0</br> [version update]
> Update 5 NuGet dependencies

- devices/Axp192/BatteryStatus.cs
- Added missing 0 to fix wrong BatteryStatus enum. 
- Added reference to where to find this enum in documentation.
- Changed name to provide clearer description of this status.
While working with sample code for Axp192 on M5Stack Core2 I've noticed that there was a duplicate status enum. While working with translated documentation I've also noticed that more fitting name to this status would be "Overheating" rather than "Overwinered"
Snippet from translated Axp192 documentation
> Fixed Axp192 battery status

- devices/Card/Mifare/MifareCard.cs
- devices/Card/Ultralight/UltralightCard.cs
- devices/Mfrc522/Mfrc522.cs
Transferred fixes and improvements from the [dotnet.iot](https://github.com/dotnet/iot) repository related to MIFARE cards.
- PR#2028 The pre-existing code assumed that there were always 4 blocks per sector and the sector trailer was always the fourth one. To handle larger sectors, this change introduces the concept of a "block group" within a sector, which represents the blocks that are associated with the access conditions. There are four block groups per sector. For sectors less than 32 there is one block per group. For sectors above 32, there are five data blocks per group; the last group is the sector trailer.
&emsp; Convenience methods to convert between block numbers and block groups were added, and they replace previously hardcoded calculations (such as blockNumber % 4) that are …
> Mifare improvements (copy-paste from dotnet.iot repo)

- devices/Dac63004/Dac63004.cs
- Fix buffer order in I2C commands.
- Some operations were setting MSB and LSB in the wrong positions.
> [Dac63004] Fix buffer order in I2C commands

- devices/Ws28xx.Esp32/BitmapImageNeo3.cs
- devices/Ws28xx.Esp32/BitmapImageNeo3RGB.cs
- devices/Ws28xx.Esp32/BitmapImageNeo4.cs
- devices/Ws28xx.Esp32/BitmapImageWs2808.cs
- devices/Ws28xx.Esp32/BitmapImageWs2808GRB.cs
- devices/Ws28xx.Esp32/Ws28xx.cs
- Made the class base `BitmapImage` class public
- Made the `ClockDivider`, `OnePulse`, `ZeroPulse`, and `ResetCommand` parameters in `ws28xx` public.
I encountered difficulties when using the Iot.Device.Ws28xx.Esp32 library due to my WS2812B device possibly being non-standard, with the model number XL-0807RGBC-WS2812B. When attempting to control it, I found that the Ws2815b in Iot.Device.Ws28xx.Esp32 could not drive it, while Ws2815c could, but the colors were reversed.
The README suggests inheriting from the Ws28xx class and making necessary modifications. However, the BitmapImageWs2808Grb and BitmapImageWs2808 classes, which could otherwise be used directly, are internal and thus cannot be inherited. Even though the source code could be inherited directly from BitmapImage, the …
> [Ws28xx.Esp32] Change visibility of several classes and properties

- devices/RgbDiode/RgbDiode.cs
- devices/RgbDiode/RgbDiode.nfproj
- devices/RgbDiode/RgbDiode.nuspec
- devices/RgbDiode/packages.config
- devices/RgbDiode/packages.lock.json
- devices/RgbDiode/samples/Program.cs
- devices/RgbDiode/samples/RgbDiode.samples.nfproj
- devices/RgbDiode/samples/packages.lock.json
- Improve computation of transition steps so it ends in the expected value.
- Change parameter type on some methods.
- Add ref to Math library in order to round and clamp RGB values.
- Update nuspec accordingly.
- Minor code style updates as the code was being changes.
- The transition was leaving "behind" the previous color component in case the steps were negative or didn't reach the final value.
> [RgbDiode] Fixes transition

- devices/Ssd13xx/README.md
Add usage instructions for IotByteFont tool to SSD13xx/SSD1306/SSD1327 & SSH1106 - OLED display family documentation
- Added usage instructions for the IotByteFont tool in the SSD13xx/SSD1306/SSD1327 & SSH1106 - OLED display family documentation. This includes installation, usage, examples, and special use cases.
- This addition provides users with detailed instructions on how to use the IotByteFont tool, which is a .NET dot matrix font creation tool. This tool is especially useful for IoT projects that require custom font rendering and is applicable to .NET nanoFramework.
- The added instructions and examples have been tested and verified to ensure accuracy and clarity.
> Add usage instructions for IotByteFont tool

- devices/Modbus/Client/ModbusClient.cs
- devices/Modbus/Port.cs
- devices/Modbus/README.md
- devices/Modbus/Server/ModbusServer.cs
- devices/Modbus/samples/Program.cs
Add an optional parameter ```(SeiralMode mode = SerialMode.RS485)``` in ModbusClient and ModbusServer constructor.
This change is to support ModBus over RS232. Current library will force set SeiralMode to RS485 which makes it does not work on Modbus over RS232 devices.
- Fixes nanoFramework/Home#1473
This modified version is tested with my [MPPTSunDevice](https://github.com/JohnMasen/MPPTSunDevice) project, which controls solar power system via Modbus over RS232.
N/A
> Add RS232 support for Modbus library

- devices/Modbus/Client/ModbusClient.cs
This is a fix for some Modbus servers not sending a marker byte as the first byte in the response.
- Resolves nanoFramework/Home#1476
Tested with several Modbus Server including a DPM6850 DC/DC Buck Converter
> [ModbusClient] Fix for startup marker in the response

- devices/Dhtxx.Esp32/DhtBase.cs
- Reset _readBuff and isLastReadSuccessful if we dont recive valid data.
- if no valid data receive from sensor, then reset _readBuff  and isLastReadSuccessful.
Scenario: Connect the sensor (DHT) to the ESP32 and read data from it. Then, unplug the sensor (DHT) from the ESP32.What Happen Now??! the ReadThroughOneWire method returns the last data, and IsLastReadSuccessful is true ! (this is not correct , when the sensor is unplugged, we expect no data be send as output), In this change, _readBuff will be clear, and IsLastReadSuccessful will be false if we don’t receive valid data form sensor.
> [Dhtxx.Esp32] Improvements when processing bad/invalid readings

- devices/GnssDevice/GenericSerialGnssDevice.cs
[GnssDevice] Adjusting for full .NET code compatibility
- Watchchar is not supported in SerialPort in the full .NET. To easy the compatibility with full .NET (used in the AtModem code for debug), adding specific code to handle the difference.
With the AtModem code
> [GnssDevice] Adjusting for full .NET code compatibility

- devices/AtModem/AtParser/AtChannel.cs
- devices/AtModem/Modem/ModemBase.cs
- Right after the lock in AtChannel.ReaderLoopAsync it is checked if _currentCommand != null. After that _currentCommand is used to do other checks.
- Sometimes these last checks give a NullReferenceException because another thread sets _currentCommand to null in the 'finally' of AtChannel.SendFullCommand. This sometimes happens after an hour or so..
- To fix this we can put a lock around the code in the 'finally' of AtChannel.SendFullCommand so the checking and using and the setting to null are mutually exclusive and the NullReferenceException doesn't happen.
- This bug is caused by multithreading in the AtChannel class. It happens in a specific situation and most of the times only after hours of http POST-ing messages.
- When this is fixed it will not cause NullReferenceExceptions
- …
> [AtModem] Fix NullReferenceException in AtChannel.ReaderLoopAsync

- devices/AtModem/Modem/ModemBase.cs
After sending "AT+CREG?" the answer sometimes doesn't contain a ','.
Like in:
• +CREG: 1,0
• +CREG: 1,0
• +CREG: 1
• +CREG: 1,1
Then an uncaught exception is thrown because of the line:
int stat = int.Parse(parts[x]);
But this doesn't happen very often. Only once every 10 networkregistrations  or so…
The fix is to check the lenght before asuming there are at least 2 parts.
- This bug sometimes causes Uncaught Exceptions. It happens only every 10 NetworkRegistrations or so.
- When the system reboots (after an Error or a watchdog trigger) the NetworkRegistration is performed again.
- When this gives an Uncaught exception the results are possibly a hanging system.
- This fix makes the system more stable.
- Fixes nanoFramework/Home#1579
- It has been tested by running the system for days …
> [AtModem] Fix Uncaught exception in ModemBase.GetNetworkRegistration()

- devices/AtModem/Http/Sim7672HttpClient.cs
The first thing that is necessary to send a HTTP message is to send the "AT+HTTPINIT" command. In the current situation when this fails, it will try it one more time and when that fails it just continues as if nothing is wrong..
The unused "Retry:" and the "int retries = 5" variable suggest that there once was a retry mechanism and in the Sim800HttpClient there is.
So I copied this retry mechanism to the Sim7672HttpClient.SendInternal, including the return of "ServiceUnavailable" when it fails after 5 retries.
I haven't noticed this gone wrong but the original implementation suggests it might. And after this fix it is handled correctly.
So it improves the stabillity of the system. And the consistence.
Signed-off-by: Rik Kreeftenberg <rik.kreeftenberg@spinsoft.nl>
This fix is required to …
> [AtModem] Fix HTTP init retry mechanism SIM7672

- devices/AtModem/AtParser/AtChannel.cs
The _currentCommand and the _currentResponse are used troughout the AtChannel class. They are set to null in the 'finally' of the AtChannel.SendFullCommand. But in very few occasions (once every hour or so) the _currentCommand is used by another thread after it has been set to null, resulting in a NullReferenceException. For example in HandleFinalResponse. This is the same multi-threading problem like the one fixed in PR #1216.
We can fix this by placing a lock around the call to AtChannel.ProcessMessage so access to _currentCommand and _currentresponse is mutually exclusive to setting them to null. So NullReference cannot occur.
This also discussed with @Ellerbach  in https://discord.com/channels/478725473862549535/1320052446227071116/1323303047895449642
Signed-off-by: Rik Kreeftenberg …
> [AtModem] Fix NullReferenceException in AtChannel.ProcessMessage

- src/device-listing/DeviceInfo.cs
- src/device-listing/Program.cs
- Add new property to hold nuget package ID.
- Add processor to grab package ID from nuspec.
- Now uses new property with package id when composing package label.
- Package ID was using a list of edge cases. 
- GSNN package not being properly labeled triggered me to improve this.
- Using the ID in nuspec makes this more robust and error free.
- Generating new README. Visually confirming that all labels are correctly generated.
> Device list CLI now uses nuspec to list NuGet package
