devices/Hcsr04/Hcsr04.nfproj
devices/Hcsr04/Hcsr04.nuspec
devices/Hcsr04/packages.config
devices/Hcsr04/samples/Program.cs

Fixing Hcsr04 for nuget generation
Fixing Hcsr04 for nuget generation
Fixing Hcsr04 for nuget generation
On a real device

Fixing Hcsr04 for nuget generation

---

src/nanoFramework.IoT.Device.CodeConverter/Program.cs

changed project guid to be deterministic; simplified solution file edits
This should simplify the solution conversion and avoid more issues.  Also, along with the project guid update, it will cut back on the number of changed files for the generated bindings.
Tested locally.
- [] New feature (non-breaking change which adds functionality)

changed project guid to be deterministic; simplified solution file edits

---

devices/LidarLiteV3/AcquisitionSettings.cs
devices/LidarLiteV3/LidarLiteV3.cs
devices/LidarLiteV3/LidarLiteV3.nfproj
devices/LidarLiteV3/LidarLiteV3.nuspec
devices/LidarLiteV3/LidarLiteV3.sln
devices/LidarLiteV3/MeasurementRepetition.cs
devices/LidarLiteV3/PowerMode.cs
devices/LidarLiteV3/Properties/AssemblyInfo.cs
devices/LidarLiteV3/README.md
devices/LidarLiteV3/Register.cs
devices/LidarLiteV3/SystemStatus.cs
devices/LidarLiteV3/category.txt
devices/LidarLiteV3/packages.config
devices/LidarLiteV3/samples/LidarLiteV3.Sample.nfproj
devices/LidarLiteV3/samples/Program.cs
devices/LidarLiteV3/samples/Properties/AssemblyInfo.cs
devices/LidarLiteV3/samples/README.md
devices/LidarLiteV3/samples/packages.config
devices/LidarLiteV3/samples/version.json
devices/LidarLiteV3/version.json

Adding LidarLiteV3
Adding LidarLiteV3
Adding LidarLiteV3
Need to be tested on a real device

Adding LidarLiteV3

---

src/devices_generated/Amg88xx/Amg88xx.nfproj
src/devices_generated/Amg88xx/Amg88xx.nuspec

- Fix assets path in nuspec.
- Fix shared project path in project file.

Fix build of Amg88xx

---

devices/Mbi5027/Mbi5027.nfproj
devices/Mbi5027/Mbi5027.nuspec
devices/Mbi5027/Mbi5027.sln
devices/Mbi5027/Mbi5027PinMapping.cs
devices/Mbi5027/packages.config
devices/Mbi5027/samples/Mbi5027-driver.nfproj
devices/Mbi5027/samples/Program.cs
devices/Mbi5027/samples/packages.config
src/devices_generated/Mbi5027/Mbi5027.sln

- Fix paths.
- Update NuGets.
- Replace reference to shiftregister.
- Fixes build.

Fix Mbi5027 build

---

azure-pipelines.yml
src/nanoFramework.IoT.Device.CodeConverter/NfNugetPackages.cs

Updated to include RuntimeEvents when Gpio required.

Updated to include RuntimeEvents when Gpio required

---

src/device-listing/Program.cs

- Add DAC category.
- Adjust path builder to point to binding folder instead of README.

Improvements in device lister

---

src/System.Numerics/Matrix3x2.cs
src/System.Numerics/Matrix4x4.cs
src/System.Numerics/Plane.cs
src/System.Numerics/Quaternion.cs
src/System.Numerics/Vector2.cs
src/System.Numerics/Vector2_Intrinsics.cs
src/System.Numerics/Vector3.cs
src/System.Numerics/Vector3_Intrinsics.cs
src/System.Numerics/Vector4.cs
src/System.Numerics/Vector4_Intrinsics.cs

- Moving away from float implementation for nano.

Sys numerics now uses doubles instead of floats

---

devices/Bmxx80/Bmxx80.nfproj
devices/Bmxx80/Bmxx80.nuspec
devices/Bmxx80/packages.config

Fix nuspec and refs on Bmxx80

---

devices/Mpr121/ChannelStatusesChangedEventArgs.cs
devices/Mpr121/Mpr121.cs
devices/Mpr121/Mpr121.nfproj
devices/Mpr121/packages.config

Fixing MPR121

---

devices/Card/Card.sln
devices/Mfrc522/Mfrc522.sln
devices/Mfrc522/samples/Mfrc522.samples.nfproj
devices/Mfrc522/samples/Program.cs
devices/Pn5180/Pn5180.cs
devices/Pn5180/Pn5180.sln
devices/Pn5180/sample/Pn5180.sample.nfproj
devices/Pn532/Pn532.sln
devices/Pn532/samples/Pn532.sample.nfproj

Fix Card.nfproj project reference

---

src/System.Numerics/System.Numerics.projitems
src/System.Numerics/Vector2.cs
src/System.Numerics/Vector3.cs
src/System.Numerics/Vector4.cs

Adjusting Vector to remove unsafe part
- Fixes issue when building the bno sensor and few others using unsafe non supported code
- Adjusting Vector to remove unsafe part

Adjusting Vector to remove unsafe part

---

devices/Ccs811/Ccs811.sln
devices/Dhtxx/Dhtxx.sln

Fixing sln projects
- Fixes sln malformed projects

Fixing sln projects

---

devices/Uln2003/Uln2003.sln
devices/Vl53L0X/Vl53L0X.sln
devices/Yx5300/Yx5300.sln

Fixing broken sln
- Fixes uln sln and few others

Fixing more sln

---

src/System.Numerics/Quaternion.cs
src/System.Numerics/Vector2.cs
src/System.Numerics/Vector4.cs

Fix Matrix4x4 build issue

---

devices/Adxl357/Adxl357.cs
devices/Max7219/Max7219.nfproj
devices/Mbi5027/Mbi5027.nfproj
devices/Mbi5027/packages.config
devices/Mbi5027/samples/Mbi5027-driver.nfproj
devices/Mbi5027/samples/packages.config
devices/Pn5180/Pn5180.sln
devices/Pn532/Pn532.sln
devices/Sn74hc595/Sn74hc595.nfproj
devices/Sn74hc595/packages.config

Fixing various build issues on IoT.Device
- Fixing various build issues on IoT.Device

Fixing various build issues on IoT.Device

---

devices/Bmxx80/Bmxx80.nfproj
devices/Bmxx80/packages.config

Fixing UnitsNet in BMxx80
- Fixes missmatch version between UnitsNet in Nuget and expected from the nfproj

Fixing UnitsNet in BMxx80

---

devices/Ak8963/README.md

- Fix 2 broken links in AK8963 README.md

Fix broken links in AK8963 README.md

---

devices/Bmxx80/README.md
devices/Bmxx80/samples/Bmp280.sample.cs
src/Iot.Device.Common/WeatherHelper.cs

- Add details about connecting to ESP32 devices.
- Improve comments in the sample code.
- Fix links to Wikipedia.
- Improve usage and sample of device

Improvements in BMxx20 sample

---

devices/System.Device.Model/System.Device.Model.nuspec

Fix System.Device.Model nuget
- I2C was present as dependency, it is not needed

Fix System.Device.Model nuget

---

devices/ServoMotor/samples/Program.cs

Adjust ServoMortor sample
- Adjust ServoMortor sample

Adjust ServoMortor sample

---

devices/Mcp3428/Mcp3428.nfproj
devices/Mcp3428/Mcp3428.nuspec
devices/Mcp3428/Mcp3428.sln
devices/Mcp3428/Mcp342x.cs
devices/Mcp3428/packages.config
devices/Mcp3428/samples/Mcp3428.Samples.nfproj
devices/Mcp3428/samples/packages.config

Fix MCP3428 deployment issue
- Fixes nanoFramework/Home#838

Fix MCP3428 deployment issue

---

README.md
migrate-binding-to-dotnetiot.md

An article to describe the steps to migrate a nanoFramework binding to .NET IoT, it provides guidance in the following areas:
- Fixing the .csproj & .sln files.
- Moving from SpanByte to Span<Byte>.
- Common nanoFramework patterns to more general .NET patters (e.g. infinite while loop).
I created the MPU6886 binding for the nanoFramework and documented the steps I took to make the binding also available in the .NET IoT repo. It could be interesting for developers who want to make their code/binding available to more .NET fans.
NA
NA

Guidance to migrate nanoFramework binding to .NET IoT

---

azure-pipelines.yml
devices/Mfrc522/Mfrc522.sln
devices/Pn5180/Pn5180.sln
devices/Pn532/Pn532.sln

- Add extra step in the pipeline to perform restore in Card solution for all NFC bindings.
- Adjusting build order for nfc readers.
- All NFC solutions depend on the Card one. nuget restore can only properly restore projects in the same solution. An extra step to restore the Card solution before building any of the NFC ones it's required in order to build in the Pipeline.

Fix Pipeline to build NFC readers

---

devices/Button/Button.sln
devices/Button/ButtonHoldingState.cs
devices/Button/GpioButton.cs

- Code improvements on the GpioButton class to make it more efficient
- Modification in .sln file
- Improvement in Button to make it more efficient, based on feedback in .NET IoT Button porting PR
- .sln file modification necessary, due to previous change in naming of Samples
- Ran current unit tests

Button improvements

---

devices/Axp192/Axp192.cs
devices/Axp192/Axp192.nfproj
devices/Axp192/Axp192.nuspec
devices/Axp192/Gpio12Behavior.cs
devices/Axp192/Gpio3Behavior.cs
devices/Axp192/Gpio4Behavior.cs
devices/Axp192/Register.cs
devices/Axp192/packages.config
devices/Axp192/samples/Axp192.samples/Axp192.samples.nfproj
devices/Axp192/samples/Axp192.samples/Program.cs
devices/Axp192/samples/Axp192.samples/packages.config

Adjusting Axp192 to expose GPIO
- Adjusting Axp192 to expose GPIO
- Fix one issue with GPIO0

Adjusting Axp192 to expose GPIO

---

devices/Axp192/Axp192.cs
devices/Axp192/Register.cs
devices/Axp192/samples/Axp192.samples/Program.cs

Adding voltage for dc-dc pins
- Adding voltage for dc-dc pins
- Adjusting LDO voltage functions as well

Adding voltage for dc-dc pins

---

devices/Max7219/Max7219.nuspec

- Fix wrong declaration on nuspec.

Fix dependency declaration on MAX7219

---

devices/Hcsr04.Esp32/Hcsr04.Esp32.cs

Improve Hcsr04 ESP32 RMT performances
- Improve Hcsr04 ESP32 RMT performances
- better long range accuracy
- Great short range one
in a real device

Improve Hcsr04 ESP32 RMT performances

---

devices/Apa102/Apa102.nfproj
devices/Apa102/Apa102.nuspec
devices/Apa102/README.md
devices/Apa102/packages.config
devices/Apa102/samples/Apa102.Samples.nfproj
devices/Apa102/samples/packages.config

Fix references for APA102

---

devices/Apa102/Apa102.nfproj
devices/Apa102/Apa102.nuspec
devices/Apa102/packages.config
devices/Apa102/samples/Apa102.Samples.nfproj
devices/Apa102/samples/packages.config

Update SPI NuGet

---

devices/Ws28xx/Ws28xx.nfproj
devices/Ws28xx/Ws28xx.nuspec
devices/Ws28xx/packages.config
devices/Ws28xx/samples/Ws28xx.Samples.nfproj
devices/Ws28xx/samples/packages.config

Fix NuGet refs in WS28xx

---

.pipeline-assets/pipeline-build-solutions.PS1

Add build "ALL" to PS Script

---

src/GenerateDocFxStructure/MessageHelper.cs
src/GenerateDocFxStructure/Program.cs

- Add const for parse error.
- Improve error message output to make it clearer.
- Improve output on error to make it clear what has to be fixed.

Improvements in docfx parser

---

devices/Ip5306/Ip5306.nfproj
devices/Ip5306/Ip5306.nuspec
devices/Ip5306/packages.config
devices/Ip5306/samples/Ip5306.samples.nfproj
devices/Ip5306/samples/packages.config

Fix references for Ip5306

---

devices/System.Drawing/System.Drawing.cs
devices/System.Drawing/System.Drawing.sln
tests/System.Drawing.Tests/ColorTests.cs
tests/System.Drawing.Tests/Properties/AssemblyInfo.cs
tests/System.Drawing.Tests/System.Drawing.Tests.nfproj
tests/System.Drawing.Tests/nano.runsettings
tests/System.Drawing.Tests/packages.config

Fixing System.Drawing color struct
- Fixing System.Drawing color struct
- Adding unit tests
Thru the unit tests.

Fixing System.Drawing color struct

---

devices/Ws28xx/BitmapImage.cs
devices/Ws28xx/BitmapImageNeo3.cs
devices/Ws28xx/BitmapImageWs2808.cs
devices/Ws28xx/Ws28xx.nfproj
devices/Ws28xx/samples/Program.cs
devices/Ws28xx/samples/Ws28xx.Samples.nfproj
devices/Ws28xx/samples/app.config
devices/Ws28xx/samples/packages.config

- Improve SetPixel implementation to have separate RGB values.

Add SetPixel as separate r g b values

---

devices/System.Diagnostics.Stopwatch/DelayHelper.cs
devices/System.Diagnostics.Stopwatch/Stopwatch.cs
devices/System.Diagnostics.Stopwatch/System.Diagnostics.Stopwatch.nfproj
devices/System.Diagnostics.Stopwatch/System.Diagnostics.Stopwatch.nuspec
devices/System.Diagnostics.Stopwatch/packages.config

Adjusting System.Diagnostic.Stopwatch to use Environment.TickCount64
- Adjusting System.Diagnostic.Stopwatch to use Environment.TickCount64
- This will improve performances

Adjusting System.Diagnostic.Stopwatch to use Environment.TickCount64

---

devices/Mcp23xxx/README.md

Fix broken link in Mcp23xxx README
- Fix broken link in Mcp23xxx README

Fix broken link in Mcp23xxx README

---

devices/Pn532/ErrorCode.cs
devices/Pn532/Pn532.cs
devices/Tsl256x/Channel.cs
devices/Tsl256x/Gain.cs
devices/Tsl256x/IntegrationTime.cs
devices/Tsl256x/InterruptControl.cs
devices/Tsl256x/InterruptPersistence.cs
devices/Tsl256x/PackageType.cs
devices/Tsl256x/Register.cs
devices/Tsl256x/Tsl256x.cs
devices/Tsl256x/samples/Program.cs
devices/Yx5300/README.md
devices/Yx5300/Yx5300.cs
devices/Yx5300/samples/Program.cs

* Fixes use of namespace `IoT` (which should be `Iot`) without renaming files or nugets.
(Converts `namespace x` and `using x` to `Iot`.)
It could go further by renaming files (which would also need changes to the CI pipeline) but that would possibly cause more issues than it is currently worth...

Breaking Change: Fix namepace

---

devices/Pcx857x/Pca8574.cs
devices/Pcx857x/Pca8575.cs
devices/Pcx857x/Pcf8574.cs
devices/Pcx857x/Pcf8575.cs
devices/Pcx857x/Pcx8574.cs
devices/Pcx857x/Pcx8575.cs
devices/Pcx857x/Pcx857x.cs
devices/Pcx857x/Pcx857x.nfproj
devices/Pcx857x/Pcx857x.sln

- Remove nullable declarations from Pcx857x.
- Move doc and config files from build to solution items.

Remove nullable declarations from Pcx857x

---

devices/System.Diagnostics.Stopwatch/Stopwatch.cs

Fixing stopwatch calculation
- Fixing stopwatch calculation
On a real device

Fixing stopwatch calculation

---

devices/Ft6xx6x/Ft6xx6x.nfproj
devices/Ft6xx6x/Ft6xx6x.nuspec
devices/Ft6xx6x/packages.config
devices/Ft6xx6x/samples/Ft6xx6x.Samples.nfproj
devices/Ft6xx6x/samples/packages.config

Update refs for Ft6xx6x

---

devices/Button/Button.nuspec
devices/Button/ButtonBase.cs
devices/Button/Tests/ButtonTests.cs
devices/Button/Tests/TestButton.cs

Fixing button behavior, improve software debounce.
- Fixes edge issues with defective / sensitive buttons
- Fixes false "holding" status and improves overall stability
With a small tact switch a bit too sensitive / ticklish
NA

Improve stability of software debounce

---

devices/AtomQrCode/AtomQrCode.nfproj
devices/AtomQrCode/packages.config

Add nbgv to Atom QrCode

---

devices/Ccs811/README.md

Code sample were using Css* instead of Ccs*

Fix a few typos in the doc: peplaced Css to Ccs 

---

devices/Axp192/AdcPinCurrentSetting.cs
devices/Axp192/Axp192.cs
devices/Axp192/Axp192.nuspec
devices/Axp192/Axp192.sln

- Add several constants to improve code.
- Fix typo in method names.
- Fix Intellisense comments.
- Improve nuspec.
- Migrate solution to VS2022.

Improvements in Axp192

---

devices/Axp192/Axp192.cs
devices/Axp192/Register.cs

- Add AXP192 registers (and respective properties in C# class) to configure PWM1.

Expose PWM1 configuration

---

devices/WeatherHelper/Properties/AssemblyInfo.cs
devices/WeatherHelper/WeatherHelper.nfproj
devices/WeatherHelper/WeatherHelper.nuspec
devices/WeatherHelper/packages.config

- Update nbgv ref.
- Fix nuspec.
- Fix assembly info file.

Various improvements in WeatherHelper

---

devices/Hcsr04.Esp32/Hcsr04.Esp32.nfproj
devices/Hcsr04.Esp32/packages.config
devices/Tcs3472x/Tcs3472x.nfproj
devices/Tcs3472x/packages.config
devices/Tlc1543/Tlc1543.nfproj
devices/Tlc1543/packages.config
devices/Tm1637/Tm1637.nfproj
devices/Tm1637/Tm1637.nuspec
devices/Tm1637/packages.config
devices/Tsl256x/Tsl256x.nfproj
devices/Tsl256x/packages.config
devices/Ws28xx.Esp32/Ws28xx.Esp32.nfproj
devices/Ws28xx.Esp32/packages.config
devices/Ws28xx.Esp32/samples/packages.config
devices/Ws28xx/Ws28xx.nfproj
devices/Ws28xx/packages.config
devices/Ws28xx/samples/packages.config

I missed some in the previous PR 😅

Bump nbgv to 3.5.107

---

devices/Axp192/Axp192.cs

- Add property to control state of EXTEN switch control.
- Need to control this pin with M5Stack TOUGH.

Add EXTENEnable property to AXP192

---

devices/A4988/A4988 .cs
devices/A4988/A4988.nfproj
devices/A4988/A4988.nuspec
devices/A4988/README.md
devices/A4988/packages.config
devices/A4988/samples/A4988.samples.nfproj
devices/A4988/samples/Program.cs
devices/A4988/samples/packages.config

- Installed UnitsNet.nanoFramework.Angle package.
- Replaced Rotate method arguments
- Adjust sample project
- Removed "sample" section from readme (it wasn't up to date). Replaced with "Please check sample project.". Easier to maintain sample project in one file :)
- Accepting multiple angle formats 
- Mentioned here: https://github.com/nanoframework/nanoFramework.IoT.Device/pull/468#pullrequestreview-1023040489
- Tested on ESP32 with TMC2208 in standalone mode (works the same as A4988) 
- VS2022 PRO with latest NF extension
- Tested UnitsNet.Angle.FromDegrees and UnitsNet.Angle.FromRadians and passing full rotation.

[A4988] Add UnitsNet.Angle and rework Rotate method

---

devices/Hx711/Hx711.Sample/Program.cs
devices/Hx711/README.md

- Add more details and clarification on WEIGHT connections and signals.
- Update README and comments on sample.
- Need to clarify connections and signals used.

[Hx711] Improvements in documentation

---

Directory.Build.props
StyleCop/README.md
StyleCop/Settings.StyleCop
StyleCop/syncSettingsOverEveryDevice.ps1
devices/AD5328/AD5328.cs
devices/AD5328/AD5328.nfproj
devices/AD5328/Properties/AssemblyInfo.cs
devices/AD5328/Settings.StyleCop
devices/AD5328/packages.config

"Simple" PS script to make sure every StyleCop settings (including packages, nfproj and stylecop.settings) are up to date in every project.
- Ran multiple times on AD5328 project

Create sync script for all devices which

---

devices/Max7219/README.md

Update the Sample as it is not working

[Max7219] Update Code to show Smiley

---

devices/Yx5300/Yx5300.cs

Fixed an error when trying to connect to the device.
It was tested on a real devices in conjunction with ESP32-WROOM-32 + DFPlayer (mini)

[Yx5300] Fix problem when try connect to device

---

devices/Pcx857x/Pcx857x.nuspec

Fix Pcx857x nuget
The nuget for the driver was referencing the wrong dll.

[Pcx857x] Fix nuget

---

devices/Ip5306/Ip5306.nfproj
devices/Ip5306/Ip5306.sln
devices/Ip5306/packages.config

- Add missing ref to nbgv.
- Fix nuspec.
- Migrate solution to VS2022.

[IP5306] Fix build and packaging

---

devices/Ina219/Ina219.cs
devices/Ina219/samples/Program.cs

- Update IoT.Device.Ina219 to support negative (reverse) current over shunt readings.
- Add MathOverflow flag read to have ability to check if last read values are correct.
- Fixes

Update Ina219 to support both side current flow readings

---

devices/Mfrc522/Mfrc522.cs
devices/Mfrc522/Mfrc522.nfproj
devices/Mfrc522/Mfrc522.nuspec
devices/Mfrc522/Mfrc522.sln
devices/Mfrc522/packages.config
devices/Mfrc522/packages.lock.json
devices/Mfrc522/samples/Mfrc522.samples.nfproj
devices/Mfrc522/samples/Program.cs
devices/Mfrc522/samples/packages.config
devices/Mfrc522/samples/packages.lock.json

- updated nuget dependencies
- switched to nuget references for "Card" etc instead of direct project references
- I couldn't use the Mfrc522 package without conflicting package / dll versions. I believe this might have had to do with direct project references maybe?
- Tested the sample app with my MFRC522 breakout board on ESP32, which worked fine

Updated mfrc522 sample

---

devices/Mpu9250/README.md

Fixed up typo in URL for Fritzing circuit diagram png
Fixed up typo in URL for Fritzing circuit diagram image.
Makes image at bottom of readme render

MPU9250 fritzing url typo fix

---

devices/Ft6xx6x/samples/Program.cs

- Add test if pin is already open so no exception is thrown.

[Ft6xx6x] Check for GPIO open

---

src/BinaryPrimitives/BinaryPrimitives.sln
src/DummyBinaryPrimitivesProject/DummyBinaryPrimitivesProject.nfproj
src/DummyBinaryPrimitivesProject/DummyClass.cs
src/DummyBinaryPrimitivesProject/Properties/AssemblyInfo.cs
src/DummyBinaryPrimitivesProject/packages.config
tests/BinaryPrimitivesUnitTests/BinaryPrimitivesTests.cs
tests/BinaryPrimitivesUnitTests/BinaryPrimitivesUnitTests.nfproj

- Add dummy project to allow building in pipeline.
- Migrate solution to VS2022.
- Fixes issues with pipeline build for the solution.

Pipeline improvements in BinaryPrimitives

---

devices/System.Numerics/Vector2.cs
devices/System.Numerics/Vector3.cs
devices/System.Numerics/Vector4.cs

Fixing vector formatting
- Fixes bug reported in Discord https://discord.com/channels/478725473862549535/605000108525748225/1066858186746896445
- Fixes Vector2.ToString(), Vector3.ToString() and Vector4.ToString()
- Aligning  the output with .NET <1 1>, <1 1 1> and <1 1 1 1>
- Removing ToString(format) as won't use and only 1 type of output will be available

[System.Numerics] Fixing vector formatting in `ToString()`

---

devices/Dhtxx.Esp32/DhtBase.cs
devices/Dhtxx.Esp32/Dhtxx.Esp32.nfproj
devices/Dhtxx.Esp32/Dhtxx.Esp32.nuspec
devices/Dhtxx.Esp32/packages.config
devices/Dhtxx.Esp32/packages.lock.json

- Update ESP32.DHTxx to the new nanoFramework.Hardware.Esp32.Rmt (2.0.1) package.
- nanoFramework.Hardware.Esp32.Rmt version 2.0.1 was released recently and brings general improvements to the RMT implementation in ESP32.
- This PR is to ensure this package is using the new set of APIs.
Tested on an ESP32 development board with a DHT22. The code deployed was from a bespoke project that and it reported the temperature and humidity levels as expected.

update the DHTxx (ESP32) to nanoFramework.Hardware.Esp32.Rmt version 2.0.1

---

devices/Bh1745/README.md

Fix broken internal link preventing docs to build
- Resolves nanoFramework/Home#1224

Fix broken internal link preventing docs to build

---

devices/Hcsr04.Esp32/Hcsr04.Esp32.cs
devices/Hcsr04.Esp32/Hcsr04.Esp32.nfproj
devices/Hcsr04.Esp32/Hcsr04.Esp32.nuspec
devices/Hcsr04.Esp32/packages.config
devices/Hcsr04.Esp32/packages.lock.json
devices/Hcsr04.Esp32/samples/Hcsr04.Samples.nfproj
devices/Hcsr04.Esp32/samples/packages.config
devices/Hcsr04.Esp32/samples/packages.lock.json

Update ESP32.HC-SR04 to the new nanoFramework.Hardware.Esp32.Rmt (2.0.1) package.
- nanoFramework.Hardware.Esp32.Rmt version 2.0.1 was released recently and brings general improvements to the RMT implementation in ESP32.
- This PR is to ensure this package is using the new set of APIs.
Tested using an ESP32 development board with a HC-SR04 module by deploying the sample project and checking the output window for received measurements.
Sample output:

update the HC-SR04 (ESP32) to nanoFramework.Hardware.Esp32.Rmt version 2.0.1

---

src/GenerateDocFxStructure/GenerateDocFxStructure.csproj

Updating DocFx generation tool to .NET 7.0
- Resolves nanoFramework/Home#1224

Updating DocFx generation tool to .NET 7.0

---

devices/Ws28xx.Esp32/Ws2812C.cs
devices/Ws28xx.Esp32/Ws2815B.cs
devices/Ws28xx.Esp32/Ws28xx.Esp32.nfproj
devices/Ws28xx.Esp32/Ws28xx.Esp32.nuspec
devices/Ws28xx.Esp32/Ws28xx.cs
devices/Ws28xx.Esp32/packages.config
devices/Ws28xx.Esp32/packages.lock.json
devices/Ws28xx.Esp32/samples/Ws28xx.Samples.nfproj
devices/Ws28xx.Esp32/samples/packages.config
devices/Ws28xx.Esp32/samples/packages.lock.json

Updated the WS28XX device binding to use the latest nanoFramework.Hardware.Esp32.Rmt (2.0.1) package. This makes use of the new RMT APIs from that package.
- nanoFramework.Hardware.Esp32.Rmt version 2.0.1 was released recently and brings general improvements to the RMT implementation in ESP32.
- This PR is to ensure this package is using the new set of APIs.
I am unable to test these changes because I don't own any of the devices supported by this binding. While the changes are refactoring to make use of the new APIs, I can't guarantee them working.

update the Ws28xx (ESP32) to nanoFramework.Hardware.Esp32.Rmt version 2.0.1

---

src/device-listing/device-listing.csproj

Updating device listing to .NET 7.0
- Fixes no more support of .NET 5.0 in pipelines

Updating device listing to .NET 7.0

---

devices/Tm1637/Tm1637.cs
devices/Tm1637/Tm1637.nfproj
devices/Tm1637/Tm1637.nuspec
devices/Tm1637/packages.config
devices/Tm1637/packages.lock.json

Improve Tm1637 performance
- Fixes nanoFramework/Home#1246
Need to be tested

Improve Tm1637 performance

---

devices/Bq2579x/Bq2579x.cs
devices/Bq2579x/Register.cs

[Bq2579x] Fix register name

---

devices/Modbus/Client/ModbusClient.cs

- Now reads dummy byte to account for frame start which is always a framing error.
- Minor code style improvements.

[Modbus] Fix client send request

---

devices/Modbus/Client/ModbusClient.cs
devices/Modbus/Server/ModbusDevice.cs
devices/Modbus/Server/ModbusServer.cs
devices/Modbus/Structures/Register.cs
devices/Modbus/Util/DataBuffer.cs
devices/Modbus/samples/Program.cs

- Change declarations on some client methods.
- Change declarations on some server methods.
- Change declaration o Register property.
- Update code as needed.

[Modbus] More changes in value type to `short`

---

devices/Dac63004/Dac63004.cs

- Rework masks to set/reset various channels current and voltage output config.
- Improve code composing register updated configuration.
- Fix byte order when sending common config register.

[Dac63004] Fix setting channel mode

---

devices/Dac63004/CodeStep.cs
devices/Dac63004/Dac63004.cs
devices/Dac63004/Dac63004.nfproj
devices/Dac63004/FunctionGeneratorExtensions.cs
devices/Dac63004/Register.cs
devices/Dac63004/SlewRate.cs
devices/Dac63004/Wave.cs

- Add new registers to config function generator.
- Add extension to generate functions.
- Add feature to control function generator.

[DAC63004] Add extension to control function generation

---

devices/SparkFunLcd/DisplaySizeEnum.cs
devices/SparkFunLcd/OpenLcdCommandEnum.cs
devices/SparkFunLcd/Properties/AssemblyInfo.cs
devices/SparkFunLcd/SparkfunLcd.cs
devices/SparkFunLcd/SparkfunLcd.sln
devices/SparkFunLcd/TextFlowDirectionEnum.cs
devices/SparkFunLcd/samples/Program.cs
devices/SparkFunLcd/samples/Properties/AssemblyInfo.cs

- Fix comment for Intellisense.
- Fix other Stylecop issues.
- Migrate solution to VS2022.
- Add missing license headers.

[SparkFunLcd] Miscelaneous improvements

---

devices/RotaryEncoder.Esp32/RotaryEncoder.Esp32.nuspec

- Remove unnecessary dependency.
- Add missing dependency.

[RotaryEncoder.Esp32] Fix nuspec

---

devices/Relay4/Relay.nfproj

[Relay4] Remove unused references

---

devices/Card/Card.nuspec

[Card] Fix nuspec

---

devices/Pn532/README.md
devices/WeatherHelper/README.md

Fix broken links into README
- Fix broken links into README

Fix broken links into README

---

devices/RgbDiode/README.md
devices/RgbDiode/RgbDiode.cs
devices/RgbDiode/samples/Program.cs

- Add missing "channel.Start" for each ADC channel
- Adjust sample code + adjust sample code in readme
- After upgrading to latest FW on ESP32 lib was not working. I've added missing Start method for each channel
- I've found a bug - looks like bug in ADC handling on native side (I don't own logic analyser so can't confirm). For now created workaround and left a comment.
- ESP32 REV0 with latest firmware

[RgbDiode] Add missing chanel start. Update sample

---

devices/AtModem/AtModem.nfproj
devices/AtModem/Events/ModemRebootedOrReadyArgs.cs
devices/AtModem/FileStorage/Sim7672FileStorage.cs
devices/AtModem/Http/Sim7672HttpClient.cs
devices/AtModem/Modem/ModemBase.cs
devices/AtModem/Modem/Sim7672.cs
devices/AtModem/Mqtt/Sim7080MqttClient.cs
devices/AtModem/Mqtt/Sim7672MqttClient.cs
devices/AtModem/Network/Sim7672Network.cs
devices/AtModem/README.md
devices/AtModem/samples/AtModem.Sample.nfproj
devices/AtModem/samples/Program.cs
devices/AtModem/samples/packages.config

Adding SIM7672 with Storage, HTTP(S), MQTT(S) and all networking including SMS and Calls
- Adding SIM7672 with Storage, HTTP(S), MQTT(S) and all networking including SMS and Calls
With the test applications

Adding SIM7672 with Storage, HTTP(S), MQTT(S) and all networking including SMS and Calls

---

devices/Lis2Mdl/Lis2Mdl.cs
devices/Lis2Mdl/Lis2Mdl.nfproj
devices/Lis2Mdl/Lis2Mdl.nuspec
devices/Lis2Mdl/Lis2Mdl.sln
devices/Lis2Mdl/Properties/AssemblyInfo.cs
devices/Lis2Mdl/README.md
devices/Lis2Mdl/Register.cs
devices/Lis2Mdl/Settings.StyleCop
devices/Lis2Mdl/category.txt
devices/Lis2Mdl/packages.config
devices/Lis2Mdl/packages.lock.json
devices/Lis2Mdl/samples/Lis2Mdl.Samples.nfproj
devices/Lis2Mdl/samples/Program.cs
devices/Lis2Mdl/samples/Properties/AssemblyInfo.cs
devices/Lis2Mdl/samples/packages.config
devices/Lis2Mdl/samples/packages.lock.json
devices/Lis2Mdl/version.json

- Add library, sample and nuspec for publish and distribuition.
- Testde with MXChip AZ3166 device.

Add binding for LIS2MDL magnetometer

---

devices/Lis2Mdl/Lis2Mdl.cs
devices/Lis2Mdl/samples/Program.cs

- Rename device ID and default address fields.
- Correct comment.
- Fix sample code accordingly.

[Lis2Mdl] Fixing field names with address and Id

---

devices/Lps22Hb/FifoMode.cs
devices/Lps22Hb/Lps22Hb.cs
devices/Lps22Hb/Lps22Hb.nfproj
devices/Lps22Hb/Lps22Hb.nuspec
devices/Lps22Hb/Lps22Hb.sln
devices/Lps22Hb/Properties/AssemblyInfo.cs
devices/Lps22Hb/README.md
devices/Lps22Hb/Register.cs
devices/Lps22Hb/Settings.StyleCop
devices/Lps22Hb/category.txt
devices/Lps22Hb/packages.config
devices/Lps22Hb/packages.lock.json
devices/Lps22Hb/samples/Lps22Hb.Samples.nfproj
devices/Lps22Hb/samples/Program.cs
devices/Lps22Hb/samples/Properties/AssemblyInfo.cs
devices/Lps22Hb/samples/packages.config
devices/Lps22Hb/samples/packages.lock.json
devices/Lps22Hb/version.json

- Add class, sample and nuspec for publishing.

Add binding for LPS22HB

---

devices/Modbus/README.md

Add limitation
Library only supports RTU

Update Modbus README.md

---

devices/Tsl256x/Tsl256x.nfproj

Fix duplicate compile statement in Tsl256x
Possible fix for nuget updates when involving project.

Fix Tsl256x

---

devices/Max1704x/Max1704X.cs

- Cap battery percent at 100% for MAX1704x sensors
- Sometime MAX17048 returned value above 100%

[MAX1704x] Cap battery percentage at 100%

---

devices/Pn532/README.md

All usages of `AsSpan()` extension changed to explicit `SpanByte` object.
Array.AsSpan() extension does not exists in current version of nf core. So documentation provides not working examples and confuses users.
Copy-pasted example code to projects, and it works without additional editing.

AsSpan extension usage changed to SpanByte

---

devices/GnssDevice/GenericSerialGnssDevice.cs
devices/GnssDevice/GnssDevice.cs
devices/GnssDevice/Messages/NmeaData.cs
devices/GnssDevice/Nmea0183Parser.cs

[GnssDevice] Minor improvements

---

devices/ePaper/Drivers/Ssd168x/Ssd168x.cs

- Fix drawing area for displays with height greater than 255
- to fix https://discord.com/channels/478725473862549535/1310919806072913951
- 128x296 2.9" ePaper display with ESP32 S3
Not Appropriate

[ePaper] Fix SetPosition for display height greater than 255

---

devices/AtModem/Http/Sim7672HttpClient.cs

When the response is processed at the end of Sim7672HttpClient.SendInternal the idea was to limit the time to 2 minutes.
Because of a logical bug this time is unlimited so when something unexpected happens and there remain bytes to read the system continues to wait indefinitely.
The while loop should read: 
While there is something left to read AND Cancelation is NOT requested
DO
Also, when the line simply reads "ERROR" then you can stop reading and break the While loop. Otherwise it will wait for 2 minutes. (Or indefinitely if the previous bug is not fixed)
This bug happens very few times. Once every couple of hours. So it's very difficult to reporoduce..
But when it does, you see the following in the logfile:
In: 
In: 
In: 
In: 
In: 
In: 
In: 
Fixing this bug restores the way this …

[AtModem] Fix system hang in sim7672 HTTP client send

---

devices/AtModem/Modem/ModemBase.cs

Implemented the `EnableNetworkDateTimeSync` method to allow synchronization of DateTime from the GSM operator. Updated the documentation for the `GetDateTime` method to include a note about enabling auto-sync before retrieving data.
Add ability to enable auto DateTime sync on modem.
- Add new method EnableNetworkDateTimeSync
- Update GetDateTime documentation
- https://discord.com/channels/478725473862549535/1329105349482909776/1330845622789603388

[AtModem] Add DateTime sync feature

---

devices/Bq2579x/Bq2579x.HelperMethods.cs
devices/Bq2579x/Bq2579x.cs
devices/Bq2579x/Bq2579x.nfproj

- Extract helper methods to a separate class.
- Required because the metadata table can't handle types with more than 255 methods.
- Compiling with new MDP.

[Bq2579x] Extract helper methods to a separate class

---

src/GenerateDocFxStructure/GenerateDocFxStructure.csproj

Bump DocFxStructure generation to .NET 9.0
Bump DocFxStructure generation to .NET 9.0
- Bump DocFxStructure generation to .NET 9.0
Locally

Bump DocFxStructure generation to .NET 9.0

---

devices/Ssd13xx/Sh1106.cs
devices/Ssd13xx/Ssd13xx.cs
devices/Ssd13xx/Ssd13xx.nfproj

Added the Sh1106 class and added internal SetPageCmd(byte[] pageCmd) to Sx13xx class 
The Sh1106 screen was not working because the PageCmd is different from the Sx1306
Tested on a Sh1106 device 
Should not affect any other area of code.

[Ssd13xx] Added Sh1106 that needs a different PageCmd
